#Logistic Regression


just for dichotomous (dicotómica)

## Libraries

In [2]:
import pandas as pd

In [3]:
db =  pd.read_csv("credito.csv")

In [4]:
db

default  proposito    tasa  v_cuota  log_ingreso  deuda_ingreso  fico  \
0           1          1  0.1189   829.10    11.350407          19.48   737   
1           1          0  0.1071   228.22    11.082143          14.29   707   
2           0          1  0.1357   366.86    10.373491          11.63   682   
3           0          1  0.1008   162.34    11.350407           8.10   712   
4           0          0  0.1426   102.92    11.299732          14.97   667   
...       ...        ...     ...      ...          ...            ...   ...   
9573        0          0  0.1461   344.76    12.180755          10.39   672   
9574        0          0  0.1253   257.70    11.141862           0.21   722   
9575        0          1  0.1071    97.81    10.596635          13.09   687   
9576        1          0  0.1600   351.58    10.819778          19.18   692   
9577        1          1  0.1392   853.43    11.264464          16.28   732   

      rotat_util  
0           52.1  
1           76.7  
2           25.6  
3           73.2  
4           39.5  
...          ...  
9573        82.1  
9574         1.1  
9575        82.9  
9576         3.2  
9577        57.0  

[9578 rows x 8 columns]

##2. Define vars

In [5]:
y=db["default"]
X=db[["tasa", "fico", "log_ingreso","deuda_ingreso","rotat_util","proposito","v_cuota"]]

## 3. Libraries

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

## 4. divding the database between train and test

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

## 5. Creating obtject or instance

In [8]:
reg=LogisticRegression()

## 6. Train the model

In [9]:
reg.fit(X_train,y_train)

LogisticRegression()

adjust reg the training database part

##7. Results

In [10]:
import numpy as np

In [11]:
reg.intercept_

array([0.00062976])

In [12]:
reg.coef_

array([[ 0.00387377, -0.0119217 , -0.02547339,  0.00946227,  0.01293638,
         0.09413763,  0.0161586 ]])

In [13]:
b=reg.coef_

In [14]:
np.exp(b[0,0])

1.0038812870046847

In [15]:
np.exp(b[0,1])

0.9881490812435465

In [16]:
np.exp(b[0,2])

0.9748483235132759

In [17]:
np.exp(b[0,3])

1.009507175086737

In [18]:
np.exp(b[0,4])

1.0130204162484815

In [19]:
np.exp(b[0,5])

1.0987109496476664

In [20]:
np.exp(b[0,6])

1.016289855875281

first ex

In [21]:
np.exp(0.00210281)

1.0021050224554675

probability that the variables is equal to 1.

Times the dependent variables is increasing or decreasing. if the result is less than 1 is because the descripted variables (tasa) is decreasing because of the dependent variables (default) and vice versa

## 8. Analysis

In [22]:
reg.score(X_train,y_train)

0.9640818599470973

## 9. Predict

In [23]:
y_pred=reg.predict(X_test)

In [24]:
y_pred

array([0, 1, 0, ..., 1, 0, 0])

## 10. Evaluating the prediction

using matrix

In [25]:
cm=confusion_matrix(y_test,y_pred)

In [26]:
cm

array([[1838,   24],
       [  63,  470]])

In [27]:
score_prediction=(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])
score_prediction

0.9636743215031315

In [28]:
db

default  proposito    tasa  v_cuota  log_ingreso  deuda_ingreso  fico  \
0           1          1  0.1189   829.10    11.350407          19.48   737   
1           1          0  0.1071   228.22    11.082143          14.29   707   
2           0          1  0.1357   366.86    10.373491          11.63   682   
3           0          1  0.1008   162.34    11.350407           8.10   712   
4           0          0  0.1426   102.92    11.299732          14.97   667   
...       ...        ...     ...      ...          ...            ...   ...   
9573        0          0  0.1461   344.76    12.180755          10.39   672   
9574        0          0  0.1253   257.70    11.141862           0.21   722   
9575        0          1  0.1071    97.81    10.596635          13.09   687   
9576        1          0  0.1600   351.58    10.819778          19.18   692   
9577        1          1  0.1392   853.43    11.264464          16.28   732   

      rotat_util  
0           52.1  
1           76.7  
2           25.6  
3           73.2  
4           39.5  
...          ...  
9573        82.1  
9574         1.1  
9575        82.9  
9576         3.2  
9577        57.0  

[9578 rows x 8 columns]